ffvb:
  csv_url: "https://www.ffvbbeach.org/ffvbapp/resu/vbspo_calendrier_export_club.php"
  csv_url_division: "https://www.ffvbbeach.org/ffvbapp/resu/vbspo_calendrier_export.php"
  address_pdf_url: "https://www.ffvbbeach.org/ffvbapp/adressier/fiche_match_ffvb.php"

club:
  name: "FS VAL D'EUROPE ESBLY COUPVRAY VB"
  id: "0775819"
  gymnases:
    - GYMNASE DAVID DOUILLET
    - DAVID DOUILLET
    - PARC DES SPORTS
    - ESPACE JEAN JACQUES LITZLER
    - Ã‰MILIE ANDEOL
  saisons:
    - 2024/2025
    - 2025/2026
